version: '3.8'

services:
  # Main AgriRAG application
  agrirag:
    build: .
    container_name: agrirag_app
    volumes:
      - ./rag_storage:/app/rag_storage
      - ./output:/app/output
      - ./LightRAG:/app/LightRAG
      - ./RAGAnything:/app/RAGAnything
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - agrirag_network
    restart: unless-stopped

networks:
  agrirag_network:
    driver: bridge
