services:
  lightrag:
    container_name: lightrag
    image: lightrag-agri:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - lightrag-agri:v1.0.0
    ports:
      - "${PORT:-9621}:9621"
    volumes:
      - ./data/rag_storage:/app/data/rag_storage
      - ./data/inputs:/app/data/inputs
      - ./config.ini:/app/config.ini
      - ./.env:/app/.env
      - ./lightrag:/app/lightrag
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
